package com.cfzd.article.bean;

import java.util.Date;

public class AccountLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_log.id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_log.account_id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_log.trans_id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer transId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_log.balance
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_log.frozen
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer frozen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_log.trans_type
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer transType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_log.trans_aount
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer transAount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_log.create_time
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_log.id
     *
     * @return the value of account_log.id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_log.id
     *
     * @param id the value for account_log.id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_log.account_id
     *
     * @return the value of account_log.account_id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_log.account_id
     *
     * @param accountId the value for account_log.account_id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_log.trans_id
     *
     * @return the value of account_log.trans_id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getTransId() {
        return transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_log.trans_id
     *
     * @param transId the value for account_log.trans_id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setTransId(Integer transId) {
        this.transId = transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_log.balance
     *
     * @return the value of account_log.balance
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_log.balance
     *
     * @param balance the value for account_log.balance
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_log.frozen
     *
     * @return the value of account_log.frozen
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getFrozen() {
        return frozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_log.frozen
     *
     * @param frozen the value for account_log.frozen
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setFrozen(Integer frozen) {
        this.frozen = frozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_log.trans_type
     *
     * @return the value of account_log.trans_type
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getTransType() {
        return transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_log.trans_type
     *
     * @param transType the value for account_log.trans_type
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setTransType(Integer transType) {
        this.transType = transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_log.trans_aount
     *
     * @return the value of account_log.trans_aount
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getTransAount() {
        return transAount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_log.trans_aount
     *
     * @param transAount the value for account_log.trans_aount
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setTransAount(Integer transAount) {
        this.transAount = transAount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_log.create_time
     *
     * @return the value of account_log.create_time
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_log.create_time
     *
     * @param createTime the value for account_log.create_time
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}