package com.cfzd.article.bean;

public class ArticleCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.type
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.name
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.icon
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.id
     *
     * @return the value of article_category.id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.id
     *
     * @param id the value for article_category.id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.type
     *
     * @return the value of article_category.type
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.type
     *
     * @param type the value for article_category.type
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.name
     *
     * @return the value of article_category.name
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.name
     *
     * @param name the value for article_category.name
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.icon
     *
     * @return the value of article_category.icon
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.icon
     *
     * @param icon the value for article_category.icon
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }
}