package com.cfzd.bean.article;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.user_id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.balance
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.frozen
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer frozen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.type
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.user_id
     *
     * @return the value of account.user_id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.user_id
     *
     * @param userId the value for account.user_id
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.balance
     *
     * @return the value of account.balance
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.balance
     *
     * @param balance the value for account.balance
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.frozen
     *
     * @return the value of account.frozen
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getFrozen() {
        return frozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.frozen
     *
     * @param frozen the value for account.frozen
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setFrozen(Integer frozen) {
        this.frozen = frozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.type
     *
     * @return the value of account.type
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.type
     *
     * @param type the value for account.type
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }
}