package com.cfzd.bean.auction;

public class AuctionImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction_image.id
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction_image.imageid
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private Integer imageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction_image.refid
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private Integer refid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction_image.type
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction_image.id
     *
     * @return the value of auction_image.id
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction_image.id
     *
     * @param id the value for auction_image.id
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction_image.imageid
     *
     * @return the value of auction_image.imageid
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public Integer getImageid() {
        return imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction_image.imageid
     *
     * @param imageid the value for auction_image.imageid
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setImageid(Integer imageid) {
        this.imageid = imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction_image.refid
     *
     * @return the value of auction_image.refid
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public Integer getRefid() {
        return refid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction_image.refid
     *
     * @param refid the value for auction_image.refid
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setRefid(Integer refid) {
        this.refid = refid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction_image.type
     *
     * @return the value of auction_image.type
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction_image.type
     *
     * @param type the value for auction_image.type
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }
}