package com.cfzd.bean.auction;

import java.util.Date;

public class Auction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction.id
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction.name
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction.endTime
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction.start_price
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private Integer startPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction.addrange
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private Integer addrange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction.deposit
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private Integer deposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction.fixed_price
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private Integer fixedPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction.userid
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction.parent
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private Integer parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auction.description
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction.id
     *
     * @return the value of auction.id
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction.id
     *
     * @param id the value for auction.id
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction.name
     *
     * @return the value of auction.name
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction.name
     *
     * @param name the value for auction.name
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction.endTime
     *
     * @return the value of auction.endTime
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction.endTime
     *
     * @param endtime the value for auction.endTime
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction.start_price
     *
     * @return the value of auction.start_price
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public Integer getStartPrice() {
        return startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction.start_price
     *
     * @param startPrice the value for auction.start_price
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setStartPrice(Integer startPrice) {
        this.startPrice = startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction.addrange
     *
     * @return the value of auction.addrange
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public Integer getAddrange() {
        return addrange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction.addrange
     *
     * @param addrange the value for auction.addrange
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setAddrange(Integer addrange) {
        this.addrange = addrange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction.deposit
     *
     * @return the value of auction.deposit
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public Integer getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction.deposit
     *
     * @param deposit the value for auction.deposit
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setDeposit(Integer deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction.fixed_price
     *
     * @return the value of auction.fixed_price
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public Integer getFixedPrice() {
        return fixedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction.fixed_price
     *
     * @param fixedPrice the value for auction.fixed_price
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setFixedPrice(Integer fixedPrice) {
        this.fixedPrice = fixedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction.userid
     *
     * @return the value of auction.userid
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction.userid
     *
     * @param userid the value for auction.userid
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction.parent
     *
     * @return the value of auction.parent
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction.parent
     *
     * @param parent the value for auction.parent
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auction.description
     *
     * @return the value of auction.description
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auction.description
     *
     * @param description the value for auction.description
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}