package com.cfzd.dao.auction;

import java.util.List;

import com.cfzd.bean.auction.Auction;

public interface AuctionMapper {
	
    List<Auction> selectByAuctionsId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int insert(Auction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int insertSelective(Auction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    Auction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int updateByPrimaryKeySelective(Auction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Auction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int updateByPrimaryKey(Auction record);
}