package com.cfzd.dao.auction;

import com.cfzd.bean.auction.Auctions;

public interface AuctionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auctions
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auctions
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int insert(Auctions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auctions
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int insertSelective(Auctions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auctions
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    Auctions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auctions
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int updateByPrimaryKeySelective(Auctions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auctions
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int updateByPrimaryKey(Auctions record);
}