package com.cfzd.dao.auction;

import com.cfzd.bean.auction.AuctionImage;

public interface AuctionImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction_image
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction_image
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int insert(AuctionImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction_image
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int insertSelective(AuctionImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction_image
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    AuctionImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction_image
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int updateByPrimaryKeySelective(AuctionImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auction_image
     *
     * @mbggenerated Sun Sep 04 20:37:00 CST 2016
     */
    int updateByPrimaryKey(AuctionImage record);
}