package com.cfzd.dao.article;

import com.cfzd.bean.article.ArticleCategory;

public interface ArticleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    int insert(ArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    int insertSelective(ArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    ArticleCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    int updateByPrimaryKeySelective(ArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbggenerated Tue Jul 19 07:10:25 CST 2016
     */
    int updateByPrimaryKey(ArticleCategory record);
}